import Head from "next/head";

export default function MoleculesPageHeader(props) {
    return (
        <Head>
            <title>
                {props.main_menu && props.sub_menu 
                    ? `${props.main_menu} | ${props.sub_menu}` 
                    : `WW2 Analytic | ${props.main_menu}`}
            </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}