import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/left_bar"

import WeaponsSummary from "../../components/summary/weapons"
import GetTotalWeaponByCountry from "./usecases/getTotalWeaponByCountry"
import GetTotalWeaponByType from "./usecases/getTotalWeaponByType"
import GetTotalWeaponBySide from "./usecases/getTotalWeaponBySide"
import GetAllWeapon from "./usecases/getAllWeapon"

export default function Weapons() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Weapons</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"weapons"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <GetAllWeapon ctx="all_weapon"/>
                            </div>
                            <div className="mb-3">
                                <GetTotalWeaponByType ctx="total_weapon_by_type"/>
                            </div>
                            <div className="mb-3">
                                <GetTotalWeaponByCountry ctx="total_weapon_by_country"/>
                            </div>
                            <div className="mb-3">
                                <GetTotalWeaponBySide ctx="total_weapon_by_side"/>
                            </div>
                            <div className="mb-3">
                                <WeaponsSummary/>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}