import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import AllWeapons from "../../components/table/allWeapons"
import TotalWeaponsByType from "../../components/barChart/totalWeaponsByType"
import TotalWeaponsByCountry from "../../components/barChart/totalWeaponsByCountry"
import TotalWeaponsBySides from "../../components/pieChart/totalWeaponsBySides"
import WeaponsSummary from "../../components/summary/weapons"

export default function Weapons() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Weapons</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"weapons"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <AllWeapons/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <TotalWeaponsByType/>
                                    </div>
                                    <WeaponsSummary/>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <TotalWeaponsByCountry/>
                                    </div>
                                    <TotalWeaponsBySides/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}