import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import AllAircraft from "../../components/table/allAircraft"
import TotalAircraftBySides from "../../components/pieChart/totalAircraftBySides"
import AircraftSummary from "../../components/summary/aircraft"
import TotalAircraftByManufacturer from "../../components/pieChart/totalAircraftByManufacturer"
import GetTotalAircraftByCountry from "./usecases/getTotalAircraftByCountry"
import GetTotalAircraftByRole from "./usecases/getTotalAircraftByRole"

export default function Aircraft() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Aircraft</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>                
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"aircraft"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <AllAircraft/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <AircraftSummary/>
                                    <TotalAircraftByManufacturer/>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <TotalAircraftBySides/>
                                </div>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <GetTotalAircraftByCountry ctx="total_aircraft_by_country"/>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <GetTotalAircraftByRole ctx="total_aircraft_by_role"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}