import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import AllEvents from "../../components/table/allEvents"

export default function Events() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Events</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="row">
                    <div className="col-3">
                        <Navbar active={"events"}/>
                    </div>
                    <div className="col-9">
                        <AllEvents/>
                    </div>
                </div>
            </main>
        </div>
    )
}