import Head from 'next/head'
import OrganismsLeftBar from '../../organisms/organisms_left_bar'

import GetAllEvent from "./usecases/getAllEvent"

export default function Events() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Events</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <div className="row">
                    <div className="col-3">
                        <OrganismsLeftBar active={"events"}/>
                    </div>
                    <div className="col-9">
                        <GetAllEvent ctx="all_event"/>
                    </div>
                </div>
            </main>
        </div>
    )
}