import Head from 'next/head'
import Navbar from "../../components/navbar/left_bar"

import FacilitiesSummary from "../../components/summary/facilities"
import GetTotalFacilityByCountry from "./usecases/getTotalFacilityByCountry"
import GetTotalFacilityByType from "./usecases/getTotalFacilityByType"
import GetTotalFacilityBySide from "./usecases/getTotalFacilityBySide"
import GetFacilityLocation from "./usecases/getFacilityLocation"

export default function Facilities() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Facilities</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"facilities"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <GetFacilityLocation ctx="facility_location"/>
                            </div>
                            <div className="mb-3">
                                <GetTotalFacilityByType ctx="total_facility_by_type"/>
                            </div>
                            <div className="mb-3">
                                <GetTotalFacilityByCountry ctx="total_facility_by_country"/>
                            </div>
                            <div className="mb-3">
                                <GetTotalFacilityBySide ctx="total_facility_by_side"/>
                            </div>
                            <div className="mb-3">
                                <FacilitiesSummary/>
                            </div>  
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}