import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import MapChart from "../../components/mapChart/totalFacilitiesByCountry"
import TotalFacilitiesBySides from "../../components/pieChart/totalFacilitiesBySides"
import FacilitiesSummary from "../../components/summary/facilities"
import GetTotalFacilityByCountry from "./usecases/getTotalFacilityByCountry"
import GetTotalFacilityByType from "./usecases/getTotalFacilityByType"

export default function Facilities() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Facilities</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"facilities"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <MapChart/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <GetTotalFacilityByType ctx="total_facility_by_type"/>
                                    </div>
                                    <FacilitiesSummary/>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <GetTotalFacilityByCountry ctx="total_facility_by_country"/>
                                    </div>
                                    <TotalFacilitiesBySides/>
                                </div>
                            </div>    
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}