import Head from 'next/head'
import Navbar from '../../components/navbar/left_bar'

// Usecases
import GetProfileInfo from './usecases/getProfileInfo'

export default function Profile() {
    return (
        <div style={{background:"#181818"}}>
            <Head>
                <title>WorldWarII | Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <div className="content">
                <div className="row">
                    <div className="col-3">
                    <OrganismsLeftBar active={"my"}/>
                    </div>
                    <div className="col-9">
                        <GetProfileInfo/>
                    </div>
                </div>
                </div>
            </main>
        </div>
    )
}