import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import TotalDeathByCountry from "../../components/columnChart/totalDeathByCountry"
import TotalDeathBySides from "../../components/pieChart/totalDeathBySides"
import CasualitiesSummary from "../../components/summary/casualities"

export default function Casualities() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Casualities</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"casualities"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <TotalDeathByCountry/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <TotalDeathBySides source={"Military"}/>     
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">  
                                    <TotalDeathBySides source={"Civilian"}/>
                                </div>
                            </div>
                            <CasualitiesSummary/>    
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}