import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import AllVehicles from "../../components/table/allVehicles"
import VehiclesSummary from "../../components/summary/vehicles"
import GetTotalVehicleByCountry from "./usecases/getTotalVehicleByCountry"
import GetTotalVehicleByRole from "./usecases/getTotalVehicleByRole"
import GetTotalVehicleBySide from "./usecases/getTotalVehicleBySide"

export default function Vehicles() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Vehicles</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"vehicles"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <AllVehicles/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                       <GetTotalVehicleByRole ctx="total_vehicle_by_role"/>
                                    </div>
                                    <VehiclesSummary/>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <GetTotalVehicleByCountry ctx="total_vehicle_by_country"/>
                                    </div>
                                    <GetTotalVehicleBySide ctx="total_vehicle_by_side"/>
                                </div>
                            </div>    
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}