import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import AllShips from "../../components/table/allShips"
import TotalShipsByLaunchYear from "../../components/radarChart/totalShipsByLaunchYear"
import ShipsSummary from "../../components/summary/ships"
import GetTotalShipByCountry from "./usecases/getTotalShipByCountry"
import GetTotalShipBySide from "./usecases/getTotalShipBySide"

export default function Ships() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Ships</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"ships"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <AllShips/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <GetTotalShipByCountry ctx="total_ship_by_country"/>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <GetTotalShipBySide ctx="total_ship_by_side"/>
                                    <ShipsSummary/>
                                    <TotalShipsByLaunchYear/> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}