import Head from 'next/head'
import OrganismsLeftBar from '../../organisms/organisms_left_bar'
import GetAllStories from './usecases/getAllStories'

export default function Story() {
  return (
    <div style={{background:"#181818"}}>
      <Head>
        <title>WorldWarII | Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="content">
          <div className="row">
            <div className="col-3">
              <OrganismsLeftBar active={"story"}/>
            </div>
            <div className="col-9">
              <div className="row">
                <GetAllStories ctx={"All_Stories"}/>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}