import Head from 'next/head'
import styles from '../../modules/styles/Home.module.css'
import Navbar from '../../components/navbar/left_bar'
import GetStoryContainer from '../../components/containers/story_container'

export default function Story() {
  return (
    <div style={{background:"#181818"}}>
      <Head>
        <title>WorldWarII | Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="content">
          <div className="row">
            <div className="col-3">
              <Navbar active={"story"}/>
            </div>
            <div className="col-9">
              <div className="row">
                {Array.from({ length: 6 }).map((_, index) => (
                  <div className="col-4" key={index}>
                    <GetStoryContainer />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}