import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/new_navbar"

import TotalBooksByYearReview from "../../components/radarChart/totalBooksByYearReview"
import BooksSummary from "../../components/summary/books"
import GetTotalBookByReviewer from "./usecases/getTotalBookByReviewer"
import GetAllBook from "./usecases/getAllBook"

export default function Books() {
    return (
        <div style={{background:"#181818"}} >
            <Head>
                <title>WorldWarII | Books</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>                
                <div className="content">
                    <div className="row">
                        <div className="col-3">
                            <Navbar active={"books"}/>
                        </div>
                        <div className="col-9">
                            <div className="mb-3">
                                <GetAllBook ctx="all_book"/>
                            </div>
                            <div className="row mb-3">
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <GetTotalBookByReviewer ctx="total_book_by_reviewer"/>
                                    </div>
                                </div>
                                <div className="col-lg-6 col-md-6 col-sm-12">
                                    <div className="mb-3">
                                        <TotalBooksByYearReview/>
                                    </div>
                                    <BooksSummary/>
                                </div>
                            </div>    
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}